### sklearn.feature_selection.chi2(X, y)[source]
Compute chi-squared stats between each non-negative feature and class.

This score can be used to select the n_features features with the highest values for the test chi-squared statistic from X, which must contain only non-negative integer feature values such as booleans or frequencies (e.g., term counts in document classification), relative to the classes.

If some of your features are continuous, you need to bin them, for example by using KBinsDiscretizer.

Recall that the chi-square test measures dependence between stochastic variables, so using this function “weeds out” the features that are the most likely to be independent of class and therefore irrelevant for classification.

#### chiSquare Returns
chi2
ndarray of shape (n_features,)
Chi2 statistics for each feature.

p_values
ndarray of shape (n_features,)
P-values for each feature.

In [26]:
import pandas as pd 
import seaborn as sns

In [27]:
df=sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [28]:
df=df[['survived','pclass','sex','embarked','alone']]

In [29]:
df.head()

   survived  pclass     sex embarked  alone
0         0       3    male        S  False
1         1       1  female        C  False
2         1       3  female        S   True
3         1       1  female        S  False
4         0       3    male        S   True

In [30]:
df.shape

(891, 5)

In [31]:
df['embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [32]:
import numpy as np
df['sex']=np.where(df['sex']=="male",1,0)

In [33]:
embarked_dict={k:i for i , k in enumerate(df['embarked'].unique(),0)}
embarked_dict

{'S': 0, 'C': 1, 'Q': 2, nan: 3}

In [34]:
df['embarked']=df['embarked'].map(embarked_dict)

   survived  pclass  sex  embarked  alone
0         0       3    1         0  False
1         1       1    0         1  False
2         1       3    0         0   True
3         1       1    0         0  False
4         0       3    1         0   True

In [35]:
df['alone']=np.where(df['alone']==True,1,0)

In [37]:
df.head()

   survived  pclass  sex  embarked  alone
0         0       3    1         0      0
1         1       1    0         1      0
2         1       3    0         0      1
3         1       1    0         0      0
4         0       3    1         0      1

In [52]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.drop('survived',axis=1),df['survived'],random_state=100,test_size=0.3)

In [53]:
from sklearn.feature_selection import chi2
f_p_values=chi2(x_train,y_train)

In [54]:
f_p_values

(array([21.97994154, 65.67929505,  7.55053653, 10.88471585]),
 array([2.75514881e-06, 5.30603805e-16, 5.99922095e-03, 9.69610546e-04]))

In [55]:
p_values=pd.Series(f_p_values[1])
p_values.index=x_train.columns
p_values.sort_index(ascending=False)

sex         5.306038e-16
pclass      2.755149e-06
embarked    5.999221e-03
alone       9.696105e-04
dtype: float64

## Observation : 
Sex column is most important columns 
higher p value means higher importance