In [2]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
import numpy as np

In [4]:
import pandas as pd 
df=pd.read_csv('titanic.csv')

In [5]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [8]:
df.drop(columns=['Name','SibSp','Ticket','Cabin','PassengerId'], inplace=True)

In [9]:
df.head()

   Survived  Pclass     Sex   Age  Parch     Fare Embarked
0         0       3    male  22.0      0   7.2500        S
1         1       1  female  38.0      0  71.2833        C
2         1       3  female  26.0      0   7.9250        S
3         1       1  female  35.0      0  53.1000        S
4         0       3    male  35.0      0   8.0500        S

In [12]:
from sklearn.model_selection import train_test_split
x=df.drop(columns=['Survived'])
y=df["Survived"]
x_train ,x_test, y_train , y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [13]:
x_test.head()

     Pclass     Sex   Age  Parch     Fare Embarked
709       3    male   NaN      1  15.2458        C
439       2    male  31.0      0  10.5000        S
840       3    male  20.0      0   7.9250        S
720       2  female   6.0      1  33.0000        S
39        3  female  14.0      0  11.2417        C

In [14]:
x_test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 268 entries, 709 to 430
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Pclass    268 non-null    int64
 1   Sex       268 non-null    object
 2   Age       215 non-null    float64
 3   Parch     268 non-null    int64
 4   Fare      268 non-null    float64
 5   Embarked  267 non-null    object
dtypes: float64(2), int64(2), object(2)
memory usage: 14.7+ KB

In [16]:
x_test.isnull().sum()

Pclass       0
Sex          0
Age         53
Parch        0
Fare         0
Embarked     1
dtype: int64

In [19]:
from sklearn.preprocessing import OneHotEncoder , OrdinalEncoder

In [28]:
transformer=ColumnTransformer(
    transformers=[
        ('imputer', SimpleImputer(), [2]),
        ('imputer2' , SimpleImputer(strategy='most_frequent'),[5]),
        ('ohe',OneHotEncoder(),[5]),
        ('oe', OrdinalEncoder() , [1])
    ], remainder='passthrough'
)

In [29]:
x_train_transform=transformer.fit_transform(x_train)

In [32]:
df_new=pd.DataFrame(x_train_transform)
df_new

             0  1    2    3    4    5    6    7    8        9
0          4.0  S  0.0  0.0  1.0  0.0  1.0  1.0  2.0  81.8583
1    29.256353  S  0.0  0.0  1.0  0.0  1.0  3.0  0.0   7.8958
2          1.0  S  0.0  0.0  1.0  0.0  0.0  3.0  1.0  11.1333
3         36.0  S  0.0  0.0  1.0  0.0  1.0  2.0  2.0    27.75
4         43.0  S  0.0  0.0  1.0  0.0  1.0  2.0  1.0    26.25
..         ... ..  ...  ...  ...  ...  ...  ...  ...      ...
618       21.0  S  0.0  0.0  1.0  0.0  0.0  3.0  0.0     7.65
619  29.256353  S  0.0  0.0  1.0  0.0  1.0  1.0  0.0     31.0
620       41.0  S  0.0  0.0  1.0  0.0  1.0  3.0  0.0  14.1083
621       14.0  S  0.0  0.0  1.0  0.0  0.0  1.0  2.0    120.0
622       21.0  S  0.0  0.0  1.0  0.0  1.0  1.0  1.0  77.2875

[623 rows x 10 columns]