In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('heart_disease_data.csv')
df.head()

   age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  ca  thal  target
0   48    1   0       130   256    1        0      150      1      0.0      2   2     3       0
1   61    1   0       148   203    0        1      161      0      0.0      2   1     3       0
2   44    0   2       118   242    0        1      149      0      0.3      1   1     2       1
3   47    1   0       110   275    0        0      118      1      1.0      1   1     2       0
4   56    1   3       120   193    0        0      162      0      1.9      1   0     3       1

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:-1],df.iloc[:,-1],test_size=0.2,random_state=2)

In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
lr_model=LogisticRegression()
Dtree_model=DecisionTreeClassifier()

In [7]:
lr_model.fit(X_train , y_train)
Dtree_model.fit(X_train , y_train)
y_pred_lr=lr_model.predict(X_test)
y_pred_tree=Dtree_model.predict(X_test)

C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

### Accracy Score

In [23]:
from sklearn.metrics import accuracy_score
print("Accuracy of LR model " ,accuracy_score(y_test,y_pred_lr) )
print("-"*80)
print("Accuracy of Tree model " ,accuracy_score(y_test,y_pred_tree) )

Accuracy of LR model  0.8524590163934426
--------------------------------------------------------------------------------
Accuracy of Tree model  0.9344262295081968

### Confusion Matrix

In [26]:
print("-"*80)
from sklearn.metrics import confusion_matrix
print(" confsion Matrix " )
print(confusion_matrix(y_test,y_pred_lr))
print("-"*80)
print(" confsion Matrix " )
print(confusion_matrix(y_test,y_pred_tree))
print("-"*80)

--------------------------------------------------------------------------------
 confsion Matrix
[[44 14]
 [ 4 60]]
--------------------------------------------------------------------------------
 confsion Matrix
[[54  4]
 [ 4 60]]
--------------------------------------------------------------------------------

### Precision

In [27]:
from sklearn.metrics import precision_score
print("Precision Score for Logistic Regression " )
print(precision_score(y_test,y_pred_lr))
print("-"*80)
print("precision Score for Decision Tree" )
print(precision_score(y_test,y_pred_tree))

Precision Score for Logistic Regression
0.8108108108108109
--------------------------------------------------------------------------------
precision Score for Decision Tree
0.9375

### Recall Score

In [22]:
from sklearn.metrics import recall_score
print("Recall Score for Logistic Regression " )
print(recall_score(y_test,y_pred_lr))
print("-"*80)
print("recall_score for Decision Tree" )
print(recall_score(y_test,y_pred_tree))

Recall Score for Logistic Regression
0.9375
--------------------------------------------------------------------------------
recall_score for Decision Tree
0.9375

In [ ]:
from sklearn.metrics import accuracy_score
print("Accuracy of LR model " ,accuracy_score(y_test,y_pred_lr) )
print("-"*80)
print("Accuracy of Tree model " ,accuracy_score(y_test,y_pred_tree) )

### F1 Score

In [28]:
from sklearn.metrics import f1_score
print("F1 Score for Logistic Regression " )
print(f1_score(y_test,y_pred_lr))
print("-"*80)
print("F1 Score for Decision Tree" )
print(f1_score(y_test,y_pred_tree))

F1 Score for Logistic Regression
0.8695652173913043
--------------------------------------------------------------------------------
F1 Score for Decision Tree
0.9375

### Understanding the Confusion matrix for multi-classification

In [30]:
print(precision_score(y_test,y_pred_lr , average=None))

[0.91666667 0.81081081]

precision_score[1]="0.81081081" USED

In [32]:
df=pd.read_csv("mnist1.5k.csv")
df.head()

   Label  Pixel 1  Pixel 2  Pixel 3  Pixel 4  Pixel 5  ...  Pixel 779  Pixel 780  Pixel 781  Pixel 782  Pixel 783  Pixel 784
0      1        0        0        0        0        0  ...          0          0          0          0          0          0
1      0        0        0        0        0        0  ...          0          0          0          0          0          0
2      1        0        0        0        0        0  ...          0          0          0          0          0          0
3      4        0        0        0        0        0  ...          0          0          0          0          0          0
4      0        0        0        0        0        0  ...          0          0          0          0          0          0

[5 rows x 785 columns]

In [34]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0:1],test_size=0.2,random_state=2)
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
lr_model=LogisticRegression()
Dtree_model=DecisionTreeClassifier() 
lr_model.fit(X_train , y_train)
Dtree_model.fit(X_train , y_train)
y_pred_lr=lr_model.predict(X_test)
y_pred_tree=Dtree_model.predict(X_test)

C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [36]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred_lr),columns=list(range(0,10)))

Logistic Regression Confusion Matrix

    0   1   2   3   4   5   6   7   8   9
0  32   0   3   0   0   0   0   0   0   0
1   0  25   0   0   0   0   0   0   1   0
2   2   2  36   1   0   0   0   0   1   0
3   0   0   2  28   0   2   0   0   0   0
4   0   0   0   0  20   0   0   0   0   0
5   0   1   1   0   0  28   0   0   1   0
6   0   0   0   0   0   0  25   0   0   0
7   0   1   0   0   0   0   0  28   0   2
8   0   1   0   1   0   3   0   0  28   1
9   0   0   0   0   1   1   0   2   1  19

In [40]:
from sklearn.metrics import precision_score 
from sklearn.metrics import precision_score
print("Precision Score for Logistic Regression " )
print(precision_score(y_test,y_pred_lr , average=None))
print(precision_score(y_test,y_pred_lr , average="macro"))
print("-"*80)
print("precision Score for Decision Tree" )
print(precision_score(y_test,y_pred_tree , average="weighted"))

Precision Score for Logistic Regression
[0.94117647 0.83333333 0.85714286 0.93333333 0.95238095 0.82352941
 1.         0.93333333 0.875      0.86363636]
0.9012866055513115
--------------------------------------------------------------------------------
precision Score for Decision Tree
0.7288002039044933

In [41]:
print("recall_score for Decision Tree" )
print(recall_score(y_test,y_pred_tree , average="weighted"))
print("F1 Score for Decision Tree" )
print(f1_score(y_test,y_pred_tree , average="macro"))

recall_score for Decision Tree
0.72
F1 Score for Decision Tree
0.7126672444716972

### Classification Report

In [43]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred_lr))

              precision    recall  f1-score   support

           0       0.94      0.91      0.93        35
           1       0.83      0.96      0.89        26
           2       0.86      0.86      0.86        42
           3       0.93      0.88      0.90        32
           4       0.95      1.00      0.98        20
           5       0.82      0.90      0.86        31
           6       1.00      1.00      1.00        25
           7       0.93      0.90      0.92        31
           8       0.88      0.82      0.85        34
           9       0.86      0.79      0.83        24

    accuracy                           0.90       300
   macro avg       0.90      0.90      0.90       300
weighted avg       0.90      0.90      0.90       300

In [44]:
print(lr_model.get_params())

{'C': 1.0, 'class_weight': None, 'dual': False, 'fit_intercept': True, 'intercept_scaling': 1, 'l1_ratio': None, 'max_iter': 100, 'multi_class': 'deprecated', 'n_jobs': None, 'penalty': 'l2', 'random_state': None, 'solver': 'lbfgs', 'tol': 0.0001, 'verbose': 0, 'warm_start': False}