In [2]:
import pandas as pd 
import numpy as np

In [3]:
df=pd.read_csv("play_tennis.csv")
df.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [4]:
df["play"].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [5]:
pPlayYes=9/(9+5)
pPlayNo=5/(9+5)

In [8]:
#for outlook
pd.crosstab(df["outlook"], df["play"])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [9]:
pPlayNoOver=0
pPlayNoRain=2/5
pPlayNoSunny=3/5

pPlayYesOver=4/9
pPlayYesRain=3/9
pPlayYesSunny=2/9

In [10]:
pd.crosstab(df["temp"], df["play"])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [16]:
pPlayNoCool=1/5
pPlayNoHot=2/5
pPlayNoMild=2/5

pPlayYesCool=3/9
pPlayYesHot=2/9
pPlayYesMild=4/9

In [12]:
pd.crosstab(df["humidity"], df["play"])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [13]:
pPlayNoHigh=4/5
pPlayNoNormal=1/5

pPlayYesHigh=3/9
pPlayYesNormal=6/9

In [14]:
pd.crosstab(df["wind"], df["play"])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [15]:
pPlayNoStrong=3/5
pPlayNoWeak=2/5

pPlayYesStrong=3/9
pPlayYesWeak=6/9

In [30]:
def NativeBayesClassifier():
    print("-"*100)
    print("Use analyze Table Tanis data and predict weather play Yes or Not based on given Condition?")
    print("Find prob When Outlook -> Sunny , Temp -> Hot , Humidity -> High and Wind -> Weak")
    print("Probability of play Yes when all condition are Giben p(Yes/Condition) : " , end="  ")
    probYesWhenCOndGiven=pPlayYes * pPlayYesSunny * pPlayYesHot * pPlayYesHigh * pPlayYesWeak
    print(probYesWhenCOndGiven)
    print("-"*100)
    print("Probability of play No when all condition are Giben p(No/Condition) : " , end="  ")
    probNoWhenCOndGiven=pPlayNo * pPlayNoSunny * pPlayNoHot * pPlayNoHigh * pPlayNoWeak
    print(probNoWhenCOndGiven)
    print("-"*100)
    print("Result will be :")
    if(probNoWhenCOndGiven>probYesWhenCOndGiven):
        print("Table Tennis is not played when all condition are given")
    else:
        print("Table Tennis is played when all condition are given")

NativeBayesClassifier()

----------------------------------------------------------------------------------------------------
Use analyze Table Tanis data and predict weather play Yes or Not based on given Condition?
Find prob When Outlook -> Sunny , Temp -> Hot , Humidity -> High and Wind -> Weak
Probability of play Yes when all condition are Giben p(Yes/Condition) :   0.007054673721340388
----------------------------------------------------------------------------------------------------
Probability of play No when all condition are Giben p(No/Condition) :   0.02742857142857143
----------------------------------------------------------------------------------------------------
Result will be :
Table Tennis is not played when all condition are given