In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('mercedesbenz.csv',usecols=['X1','X2'])
df

     X1  X2
0     v  at
1     t  av
2     w   n
3     t   n
4     v   n
...  ..  ..
4204  s  as
4205  o   t
4206  v   r
4207  r   e
4208  r  ae

[4209 rows x 2 columns]

In [ ]:
pd.get_dummies(df).shape

(4209, 71)

here we have (4209,71) shaped data when we perform simple one hot encoding.
this causes increase dimensionality of data and can cause overfitting.
we are encoding my replacing it with  count

In [ ]:
count=df.X2.value_counts().to_dict()
count

{'as': 1659,
 'ae': 496,
 'ai': 415,
 'm': 367,
 'ak': 265,
 'r': 153,
 'n': 137,
 's': 94,
 'f': 87,
 'e': 81,
 'aq': 63,
 'ay': 54,
 'a': 47,
 't': 29,
 'k': 25,
 'i': 25,
 'b': 21,
 'ao': 20,
 'z': 19,
 'ag': 19,
 'd': 18,
 'ac': 13,
 'g': 12,
 'ap': 11,
 'y': 11,
 'x': 10,
 'aw': 8,
 'at': 6,
 'h': 6,
 'q': 5,
 'al': 5,
 'an': 5,
 'av': 4,
 'p': 4,
 'ah': 4,
 'au': 3,
 'am': 1,
 'j': 1,
 'af': 1,
 'l': 1,
 'aa': 1,
 'c': 1,
 'o': 1,
 'ar': 1}

In [ ]:
df['X2']=df['X2'].map(count)

In [ ]:
df.head()

  X1   X2
0  v    6
1  t    4
2  w  137
3  t  137
4  v  137