### Target Giuded Ordinal Encoding
1. Ording the label according the label
2. Replace the label by the joint probability of being o and 1.  
Target Guided Ordinal Encoding is a categorical encoding technique where categories are ordered based on their relationship with the target variable.

#### Advantage:
1. Precise mapping :
  Categories are mapped using their actual relationship with the target (mean encoding).

2. Creates a monotonic relationship :
   Helps linear models (Logistic Regression, Linear Regression) learn patterns more effectively.

   
3. Handles high-cardinality features well :
   More efficient than one-hot encoding when categories are many.

#### Disadvantage: 
1. Prone to overfitting :
Especially when a category has very few samples.

2. Target leakage risk :
If encoding is done before train–test split.

3. Sensitive to noise :
Small changes in data can change category rankings.

In [20]:
import pandas as pd 
import numpy as np

In [21]:
df=pd.read_csv('titanic.csv',usecols=['Cabin','Survived'])

In [22]:
df.head()

   Survived Cabin
0         0   NaN
1         1   C85
2         1   NaN
3         1  C123
4         0   NaN

In [23]:
df['Cabin'].fillna('Missing',inplace=True)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_7340\321717856.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Cabin'].fillna('Missing',inplace=True)

In [24]:
df.head()

   Survived    Cabin
0         0  Missing
1         1      C85
2         1  Missing
3         1     C123
4         0  Missing

In [25]:
df.isnull().sum()

Survived    0
Cabin       0
dtype: int64

In [26]:
df['Cabin']=df["Cabin"].astype(str).str[0]

In [32]:
ordinal_label=df.groupby(['Cabin'])['Survived'].mean().to_dict() #probability of surviving for each seat
ordinal_label

{'A': 0.4666666666666667,
 'B': 0.7446808510638298,
 'C': 0.5932203389830508,
 'D': 0.7575757575757576,
 'E': 0.75,
 'F': 0.6153846153846154,
 'G': 0.5,
 'M': 0.29985443959243085,
 'T': 0.0}

In [29]:
df['Cabin_ordinal_label']=df['Cabin'].map(ordinal_label)

In [30]:
df.head()

   Survived Cabin  Cabin_ordinal_label
0         0     M             0.299854
1         1     C             0.593220
2         1     M             0.299854
3         1     C             0.593220
4         0     M             0.299854

In [ ]:
df.dtypes