### Target Giuded Ordinal Encoding
1. Ording the label according the label
2. Replace the label by the joint probability of being o and 1.

In [2]:
import pandas as pd 
import numpy as np

In [10]:
df=pd.read_csv('titanic.csv',usecols=['Cabin','Survived'])

In [11]:
df.head()

   Survived Cabin
0         0   NaN
1         1   C85
2         1   NaN
3         1  C123
4         0   NaN

In [12]:
df['Cabin'].fillna('Missing',inplace=True)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_3388\321717856.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Cabin'].fillna('Missing',inplace=True)

In [13]:
df.head()

   Survived    Cabin
0         0  Missing
1         1      C85
2         1  Missing
3         1     C123
4         0  Missing

In [14]:
df.isnull().sum()

Survived    0
Cabin       0
dtype: int64

In [16]:
df['Cabin']=df["Cabin"].astype(str).str[0]

In [22]:
ordinal_label=df.groupby(['Cabin'])['Survived'].mean().sort_values().index   #probability of surviving for each seat
ordinal_label

Index(['T', 'M', 'A', 'G', 'C', 'F', 'B', 'E', 'D'], dtype='object', name='Cabin')

In [26]:
ordinal_level2={k : i for i, k in enumerate(ordinal_label,0)}

In [27]:
ordinal_level2

{'T': 0, 'M': 1, 'A': 2, 'G': 3, 'C': 4, 'F': 5, 'B': 6, 'E': 7, 'D': 8}

In [33]:
df['Cabin_ordinal_label']=df['Cabin'].map(ordinal_level2)

In [31]:
df.head()

   Survived  Cabin
0         0      1
1         1      4
2         1      1
3         1      4
4         0      1

In [32]:
df.dtypes

Survived    int64
Cabin       int64
dtype: object