#### capturing nan value with New Feature 
it works well if data are not missing completely at random.

In [4]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('titanic.csv',usecols=['Age','Survived','Fare'])
df.head()

   Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [3]:
df.shape

(891, 3)

In [7]:
df['Age_nan']= np.where(df['Age'].isnull(),1,0)
df[df['Age'].isnull()].head()

    Survived  Age     Fare  Age_nan
5          0  NaN   8.4583        1
17         1  NaN  13.0000        1
19         1  NaN   7.2250        1
26         0  NaN   7.2250        1
28         1  NaN   7.8792        1

##### Advantage of replacinf NaN value with new Feature
1. easy to implement
2. Capture the importance of missing Value

##### Disadvantage: 
1. create additional Column (curse of dimentionality)

In [8]:
df['Age'].fillna(df['Age'].median(),inplace=True)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_28468\1527141296.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].median(),inplace=True)

In [10]:
df.head(15)    # here we have new feature i.e Age_nan

    Survived   Age     Fare  Age_nan
0          0  22.0   7.2500        0
1          1  38.0  71.2833        0
2          1  26.0   7.9250        0
3          1  35.0  53.1000        0
4          0  35.0   8.0500        0
5          0  28.0   8.4583        1
6          0  54.0  51.8625        0
7          0   2.0  21.0750        0
8          1  27.0  11.1333        0
9          1  14.0  30.0708        0
10         1   4.0  16.7000        0
11         1  58.0  26.5500        0
12         0  20.0   8.0500        0
13         0  39.0  31.2750        0
14         0  14.0   7.8542        0