In [45]:
x=[1,2,3,4,5]
y=[2,4,5,4,5]
import pandas as pd
df=pd.DataFrame({'X':x,
                 'Y':y})

In [46]:
df

   X  Y
0  1  2
1  2  4
2  3  5
3  4  4
4  5  5

In [47]:
X=df[['X']]
Y=df["Y"]
X

   X
0  1
1  2
2  3
3  4
4  5

In [48]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()
regressed=reg.fit(X,Y)

In [49]:
R2_SCORE=reg.score(X,Y)

In [50]:
R2_SCORE

0.6000000000000001

In [51]:
reg.predict([  [2] ,[3],[4],[5],[6]])

C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([3.4, 4. , 4.6, 5.2, 5.8])

In [56]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaled_df=pd.DataFrame(scaler.fit_transform(df),columns=['X','Y'])

In [57]:
X=scaled_df[['X']]
Y=scaled_df["Y"]
X

          X
0 -1.414214
1 -0.707107
2  0.000000
3  0.707107
4  1.414214

In [61]:
Y

0   -1.825742
1    0.000000
2    0.912871
3    0.000000
4    0.912871
Name: Y, dtype: float64

In [58]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()
regressed=reg.fit(X,Y)

In [59]:
R2_SCORE=reg.score(X,Y)

In [60]:
R2_SCORE

0.6

In [62]:
from sklearn.metrics import r2_score
r2_score(X,Y)    #r2_score(y_test,y_pred)

0.5491933384829668