In [17]:
from io import StringIO #read different data source with the help of pandas
import pandas as pd

In [18]:
df=pd.read_csv("mercedesbenz.csv")
df.head()

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0

In [19]:
data=('col1,col2,col3\n' 'x,y,2 \n' 'a,b,4\n' 'c,d,3')
type(data)
print(data)

col1,col2,col3
x,y,2
a,b,4
c,d,3

In [20]:
pd.read_csv(StringIO(data),usecols=["col1","col2"])

  col1 col2
0    x    y
1    a    b
2    c    d

In [21]:
df=pd.read_csv("mercedesbenz.csv",usecols=['X0','X1','X2','X3','X4'])
df

      X0 X1  X2 X3 X4
0      k  v  at  a  d
1      k  t  av  e  d
2     az  w   n  c  d
3     az  t   n  f  d
4     az  v   n  f  d
...   .. ..  .. .. ..
4204  ak  s  as  c  d
4205   j  o   t  d  d
4206  ak  v   r  a  d
4207  al  r   e  f  d
4208   z  r  ae  c  d

[4209 rows x 5 columns]

In [22]:
df.to_csv("new_mercedes")

In [25]:
data=('a,b,c,d\n' '1,3,2,7 \n' '5,6,4,4\n' '7,8,3')
df=pd.read_csv(StringIO(data),dtype={"a":int,"b":float,"c":object})
df

   a    b  c    d
0  1  3.0  2  7.0
1  5  6.0  4  4.0
2  7  8.0  3  NaN

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       3 non-null      int64
 1   b       3 non-null      float64
 2   c       3 non-null      object
 3   d       2 non-null      float64
dtypes: float64(2), int64(1), object(1)
memory usage: 228.0+ bytes

In [27]:
df.isnull().sum()

a    0
b    0
c    0
d    1
dtype: int64

In [37]:
data2=('index,a,b,c\n''4,bat,apple,5.7\n''8,oarnge,cow,10')
pd.read_csv(StringIO(data2),index_col=0)

            a      b     c
index
4         bat  apple   5.7
8      oarnge    cow  10.0

In [39]:
#use index column and use columns
pd.read_csv(StringIO(data2),usecols=['b','c'])

       b     c
0  apple   5.7
1    cow  10.0

In [44]:
pd.read_csv('cu.item',sep='\t')

,item_code,item_name,display_level,selectable,sort_sequence
0,AA0,All items - old base,0,T,2
1,AA0R,Purchasing power of the consumer dollar - old ...,0,T,400
2,SA0,All items,0,T,1
3,SA0E,Energy,1,T,375
4,SA0L1,All items less food,1,T,359
...,...,...,...,...,...
395,SSEA011,College textbooks,3,T,314
396,SSEE041,Smartphones,4,T,335
397,SSFV031A,Food at elementary and secondary schools,3,T,122
398,SSGE013,Infants' equipment,3,T,356
399,SSHJ031,Infants' furniture,3,T,165